### ISSUE TITLE
Comments on homework

### ISSUE THREAD

**Issue by paeby** [fdevillard/ada-homeworks#3]
Exercise of "Intro to pandas": well commented and good Python

First exercise of "Data Wrangling": I think the goal was to add columns Barcode, Group and Sample and write the corresponding values in each row. There are no comments justifying why you chose to do it in this way. And I don't find it really clean to add manually the names of the columns, you could obtain them directly from the file that describes the content. But the counts in the cells is correct :)

Second exercise of "Data Wrangling": description of columns good (additional plots would have been nice). Point 2: answer's right but try to use functions already defined in Python.

**Comment by fdevillard** [comment]
Thanks for the correction :)
